from threading import Event, Thread
from HTMLParser import HTMLParser
from bs4 import BeautifulSoup
import psycopg2
import requests
import urllib
import os
import time
import json

rockNRollHallOfFame = [
"Chuck Berry",
"James Brown",
"Ray Charles",
"Sam Cooke",
"Fats Domino",
"Buddy Holly",
"Jerry Lee Lewis",
"Elvis Presley",
"Eddie Cochran",
"Bo Diddley",
"Aretha Franklin",
"Marvin Gaye",
"Bill Haley",
"B.B. King",
"Clyde McPhatter",
"Ricky Nelson",
"Roy Orbison",
"Carl Perkins",
"Smokey Robinson",
"Big Joe Turner",
"Muddy Waters",
"Jackie Wilson",
"Bob Dylan",
"Otis Redding",
"Stevie Wonder",
"Hank Ballard",
"Bobby Darin",
"LaVern Baker",
"John Lee Hooker",
"Wilson Pickett",
"Jimmy Reed",
"Ike & Tina Turner",
"Johnny Cash",
"The Jimi Hendrix Experience",
"Ruth Brown",
"Frankie Lymon & The Teenagers",
"Etta James",
"Van Morrison",
"Duane Eddy",
"Elton John",
"John Lennon",
"Bob Marley",
"Rod Stewart",
"Al Green",
"Janis Joplin",
"Neil Young",
"Frank Zappa",
"David Bowie",
"Gladys Knight & the Pips",
"The Jackson 5",
"Joni Mitchell",
"Lloyd Price",
"Gene Vincent",
"Billy Joel",
"Curtis Mayfield",
"Paul McCartney",
"Del Shannon",
"Dusty Springfield",
"Bruce Springsteen",
"The Staple Singers",
"Eric Clapton",
"The Lovin Spoonful",
"The Moonglows",
"Bonnie Raitt",
"James Taylor",
"Solomon Burke",
"The Flamingos",
"Michael Jackson",
"Paul Simon",
"Ritchie Valens",
"Isaac Hayes",
"Brenda Lee",
"Tom Petty and the Heartbreakers",
"Gene Pitney",
"The Clash",
"Elvis Costello & the Attractions",
"The Police",
"The Righteous Brothers",
"Jackson Browne",
"The Dells",
"George Harrison",
"Bob Seger",
"Buddy Guy",
"The O Jays",
"Percy Sledge",
"Miles Davis",
"The Ronettes",
"Patti Smith",
"The Dave Clark Five",
"Leonard Cohen",
"John Mellencamp",
"The Ventures",
"Jeff Beck",
"Bobby Womack",
"Jimmy Cliff",
"The Hollies",
"The Stooges",
"Neil Diamond",
"Darlene Love",
"Tom Waits",
"Laura Nyro",
"Albert King",
"Randy Newman",
"Donna Summer",
"Peter Gabriel",
"Linda Ronstadt",
"Cat Stevens",
"The Paul Butterfield Blues Band",
"Joan Jett & the Blackhearts",
"Lou Reed",
"Stevie Ray Vaughan",
"Bill Withers",
"Steve Miller",
"Joan Baez"
]

eightiesArtists = [
"Michael Jackson",
"Prince",
"Madonna",
"U2",
"Bruce Springsteen",
"Run-D.M.C.",
"Van Halen",
"Public Enemy",
"Billy Joel",
"The Police",
"Phil Collins",
"Guns N Roses",
"Def Leppard",
"Janet Jackson",
"George Michael",
"Wham",
"Whitney Houston",
"Metallica",
"N.W.A",
"Dire Straits",
"AC/DC",
"Rush",
"Iron Maiden",
"Judas Priest",
"Lionel Richie",
"Bon Jovi",
"Talking Heads",
"Genesis",
"R.E.M.",
"Duran Duran",
"Motley Crue",
"The Cure",
"Journey",
"John Mellencamp",
"Grandmaster Flash & The Furious Five",
"REO Speedwagon",
"Kool and the Gang",
"L.L. Cool J",
"Tina Turner",
"Queen",
"Beastie Boys",
"Ozzy Osbourne",
"The Smiths",
"Huey Lewis and the News",
"Bryan Adams",
"Hall & Oates",
"Pat Benatar",
"Eric B. & Rakim",
"Billy Idol",
"Peter Gabriel",
"INXS",
"Tom Petty & the Heartbreakers",
"Stevie Ray Vaughan & Double Trouble",
"Eurythmics",
"The Cars",
"Aerosmith",
"ZZ Top",
"The Rolling Stones",
"Heart",
"David Bowie",
"Elton John",
"Rod Stewart",
"Foreigner",
"Stevie Wonder",
"Toto",
"Bob Seger",
"The Pointer Sisters",
"DJ Jazzy Jeff & The Fresh Prince",
"Salt-N-Pepa",
"Fleetwood Mac",
"The Go-Gos",
"Paul McCartney",
"Pet Shop Boys",
"Don Henley",
"Paul Simon",
"Tracy Chapman",
"Cyndi Lauper",
"Depeche Mode",
"Sonic Youth",
"Pete Townshend",
"Culture Club",
"Gloria Estefan Miami Sound Machine",
"De La Soul",
"Luther Vandross",
"Chicago",
"The Bangles",
"Thompson Twins",
"Yes",
"Men at Work",
"Pixies",
"Pink Floyd",
"Robert Palmer",
"Kenny Loggins",
"Whitesnake",
"Sade",
"Steve Winwood",
"Billy Ocean",
"Tears for Fears",
"Bobby Brown",
"Scorpions",
"Simply Red",
"B-52s",
"Boston",
"Rick James",
"Joan Jett",
"Stevie Nicks",
"Berlin",
"Sting",
"New Order",
"Poison",
"The Pretenders",
"Quiet Riot",
"RATT",
"The Clash",
"The Stone Roses",
"Squeeze",
"Styx",
"Frankie Goes to Hollywood",
"New Edition",
"Stray Cats",
"Paula Abdul",
"The Human Leagu",
"Violent Femmes",
"Elvis Costello",
"A-Ha",
"Blondie",
"Eddie Money",
"Anita Baker",
"Sheena Easton",
"Loverboy",
"Asia",
"Skid Row",
"Tiffany",
"Debbie Gibson",
"Crosby Stills Nash (& Young)",
"Madness",
"Aretha Franklin",
"Afrika Bambaataa",
"UB 40",
"Patti LaBelle",
"Tone-Loc",
"Falco",
"Simple Minds",
"Earth Wind & Fire",
"KISS",
"The Jam",
"Marvin Gaye",
"Bananarama",
"New Kids on the Block",
"Billy Squier",
"Slayer",
"Adam Ant",
"Spandau Ballet",
"Milli Vanilli",
"The Jesus and Mary Chain",
"ABC",
"Cinderella",
"Bonnie Raitt",
"10,000 Maniacs",
"Accept",
"Eric Clapton",
"Kool Moe Dee",
"The Cult",
"The Fixx",
"Air Supply",
"Richard Marx",
"Bruce Hornsby & the Range",
"Starship",
"The Replacements",
"Fine Young Cannibals",
"Mr. Mister",
"Boogie Down Productions",
"Irene Cara",
"David Lee Roth",
"Twisted Sister",
"Corey Hart",
"Doug E. Fresh",
"Laura Branigan",
"Dio",
"Dokken",
"A Flock of Seagulls",
"Eddy Grant",
"Black Flag",
"Dead Kennedys",
"George Thorogood",
"John Lennon",
"Terence Trent Darby",
"Red Hot Chili Peppers",
"Rick Springfield",
"Paul Young",
"Black Sabbath",
"Howard Jones",
"Orchestral Manoeuvres in the Dark",
"Level 42",
"Europe",
"Tom Waits",
"Mike Oldfield",
"Chris De Burgh",
"Alan Parsons Project",
"John Farnham"
]

ninetiesArtists = [
"Nirvana",
"2Pac",
"Mariah Carey",
"Pearl Jam",
"Madonna",
"R.E.M.",
"U2",
"Dr. Dre",
"Red Hot Chili Peppers",
"The Smashing Pumpkins",
"The Notorious B.I.G",
"OutKast",
"Janet Jackson",
"Radiohead",
"Green Day",
"Fugees/Lauryn Hill",
"Metallica",
"Ice Cube",
"Oasis",
"TLC",
"Alice In Chains",
"Snoop Dogg",
"Nine Inch Nails",
"Nas",
"Beastie Boys",
"Rage Against The Machine",
"Jay-Z",
"A Tribe Called Quest",
"Mary J. Blige",
"Beck",
"Soundgarden",
"Public Enemy",
"Wu-Tang Clan",
"Alanis Morissette",
"Guns N Roses",
"Queen Latifah",
"Dave Matthews Band",
"No Doubt",
"Prince",
"Michael Jackson",
"R. Kelly",
"En Vogue",
"Tori Amos",
"Missy Elliot",
"Jeff Buckley",
"Weezer",
"PJ Harvey",
"Blur",
"Tool",
"Sonic Youth",
"Stone Temple Pilots",
"Jane's Addiction",
"Eric Clapton",
"Boyz II Men",
"Seal",
"Bush",
"Fugazi",
"Sinead O' Conner",
"Cypress Hill",
"The Roots",
"The Offspring",
"Neil Young",
"Sublime",
"Marilyn Manson",
"Pantera",
"Liz Phair",
"Pavement",
"Coolio",
"Korn",
"Foo Fighters",
"My Bloody Valentine",
"Black Crowes",
"Silver Chair",
"The Verve",
"Phish",
"311",
"Hole",
"The Flaming Lips",
"Lenny Kravitz",
"Nick Cave & The Bad Seeds",
"Sheryl Crow",
"Megadeth",
"Faith No More",
"Queen",
"Cranberries",
"Busta Rhymes",
"Warren G.",
"The Mighty Mighty Bosstones",
"Kenny Wayne Shepherd Band",
"D Angelo",
"Creed",
"Arrested Development",
"Blind Melon",
"Manic Street Preachers",
"Garbage",
"Screaming Trees",
"Hootie & The Blowfish",
"Primus",
"Wilco"
]

test = [
"Bill Withers"
]

artistsBumped = 0
for artist in test:
  artistLowercase = artist.lower();
  artistEncoded = urllib.quote(artistLowercase)
  url="http://localhost:5000/search?query=" + artistEncoded + "&type=artist&method=indexed"
  headers={
    "User-Agent" :
    "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
  }

  r = requests.get(url, headers=headers)
  soup = BeautifulSoup(r.content, "html.parser")
  trs = soup.findAll("tr")
  td1 = trs[1].findAll('td')[0]
  topScore  = td1.getText()

  if topScore  == "100":
    tr1 = trs[1]
    td1 = tr1.findAll('td')[1]
    if td1.find('bdi').getText().lower() == artistLowercase:
      artistsBumped += 1
      print "Artists bumped so far", artistsBumped
      link = td1.find('a')
      artistMbid = link['href'].replace('/artist/', '')
      elasticSearchUrl = 'http://localhost:9200/artists/artist/' + artistMbid
      elasticSearchRequest = requests.get(elasticSearchUrl, headers=headers)
      jsonResponse = json.loads(elasticSearchRequest.content)
      views = jsonResponse['_source']['views']

      if views == 0:
        # make a request to bump the views by 100
        data = { "script" : "ctx._source.views+=100" }
        payload = json.dumps(data)
        requests.post(elasticSearchUrl + "/_update", headers=headers, data=payload)
      else :
        # log that artist has been already bumped
        print jsonResponse['_source']['name'], "already bumped, views:", jsonResponse['_source']['views']

      # Make a request to get all artists albums and bump those by mbid if not already bumped
      # then call last fm and get all related artists and log those to a file (to be run against this script later)
    else:
      print "artist name no match"
      # write a log file that artist names dont match
  else:
    print "First cell not top score"
    # make a log here
  time.sleep(10)
