from threading import Event, Thread
from HTMLParser import HTMLParser
from bs4 import BeautifulSoup
import psycopg2
import requests
import urllib2
import os
import time
import json

rockNRollHallOfFame = [
"Chuck Berry",
"James Brown",
"Ray Charles",
"Sam Cooke",
"Fats Domino",
"Buddy Holly",
"Jerry Lee Lewis",
"Elvis Presley",
"Eddie Cochran",
"Bo Diddley",
"Aretha Franklin",
"Marvin Gaye",
"Bill Haley",
"B.B. King",
"Clyde McPhatter",
"Ricky Nelson",
"Roy Orbison",
"Carl Perkins",
"Smokey Robinson",
"Big Joe Turner",
"Muddy Waters",
"Jackie Wilson",
"Bob Dylan",
"Otis Redding",
"Stevie Wonder",
"Hank Ballard",
"Bobby Darin",
"LaVern Baker",
"John Lee Hooker",
"Wilson Pickett",
"Jimmy Reed",
"Ike & Tina Turner",
"Johnny Cash",
"The Jimi Hendrix Experience",
"Ruth Brown",
"Frankie Lymon & The Teenagers",
"Etta James",
"Van Morrison",
"Duane Eddy",
"Elton John",
"John Lennon",
"Bob Marley",
"Rod Stewart",
"Al Green",
"Janis Joplin",
"Neil Young",
"Frank Zappa",
"David Bowie",
"Gladys Knight & the Pips",
"The Jackson 5",
"Joni Mitchell",
"Lloyd Price",
"Gene Vincent",
"Billy Joel",
"Curtis Mayfield",
"Paul McCartney",
"Del Shannon",
"Dusty Springfield",
"Bruce Springsteen",
"The Staple Singers",
"Eric Clapton",
"The Lovin Spoonful",
"The Moonglows",
"Bonnie Raitt",
"James Taylor",
"Solomon Burke",
"The Flamingos",
"Michael Jackson",
"Paul Simon",
"Ritchie Valens",
"Isaac Hayes",
"Brenda Lee",
"Tom Petty and the Heartbreakers",
"Gene Pitney",
"The Clash",
"Elvis Costello & the Attractions",
"The Police",
"The Righteous Brothers",
"Jackson Browne",
"The Dells",
"George Harrison",
"Bob Seger",
"Buddy Guy",
"The O Jays",
"Percy Sledge",
"Miles Davis",
"The Ronettes",
"Patti Smith",
"The Dave Clark Five",
"Leonard Cohen",
"John Mellencamp",
"The Ventures",
"Jeff Beck",
"Bobby Womack",
"Jimmy Cliff",
"The Hollies",
"The Stooges",
"Neil Diamond",
"Darlene Love",
"Tom Waits",
"Laura Nyro",
"Albert King",
"Randy Newman",
"Donna Summer",
"Peter Gabriel",
"Linda Ronstadt",
"Cat Stevens",
"The Paul Butterfield Blues Band",
"Joan Jett & the Blackhearts",
"Lou Reed",
"Stevie Ray Vaughan",
"Bill Withers",
"Steve Miller",
"Joan Baez"
]

seventiesArtists= [
"10CC",
".38 SPECIAL",
"Abba",
"Abraham's Children",
"AC/DC",
"The Adverts",
"Aerosmith",
"Affinity",
"Al Green",
"Al Stewart",
"Albert Hammond",
"ALBERT KING",
"Alice Cooper",
"Allman Brothers",
"The Amboy Dukes",
"Ambrosia",
"America",
"Andy Gibb",
"April Wine",
"Aretha Franklin",
"Argent",
"Armageddon",
"Art Garfunkel",
"Atlanta Rhythm Section",
"Atomic Rooster",
"Average White Band",
"Axe",
"B. B. KING",
"B. J. Thomas",
"Babe Ruth",
"The Babys",
"Bachman Turrner Overdrive",
"Bad Company",
"Badfinger",
"The Band",
"Barbara Streisand",
"Barry White",
"Bay City Rollers",
"Beach Boys",
"Beaver Brown Band",
"Bee Gees",
"Belamy Brothers",
"Big Star",
"Bill Haley & His Comets",
"Bill Withers",
"Billy Joel",
"Billy Preston",
"Black Oak Arkansas",
"BLACK SABBATH",
"Blackfeather",
"Blondie",
"BLOOD & SWEAT & TEARS",
"Blue",
"Blue Cheer",
"Blue Oyster Cult",
"Blues Creation",
"Blues Image",
"BOB DYLAN",
"Bob Marley & The Wailers",
"Bobby Womack",
"BOB SEGAR",
"BOB SEGAR AND THE SILVER BULLET BAND",
"Bob Welch",
"Boney M",
"Bonnie Tyler",
"BONNIE RAITT",
"Boomtown Rats",
"Boston",
"BOZ SCAGGS",
"Bread",
"Breakfast Club",
"BREWER AND SHIPLEY",
"Brian Eno",
"Brotherhood of Man",
"Brownsville Station",
"Bruce Springsteen",
"Budgie",
"The Buggles",
"Buzzcocks",
"Cactus",
"Can",
"Canadian Sweethearts",
"Canned Heat",
"Captain & Tennille",
"Captain Beefheart",
"Carly Simon",
"CAROLE KING",
"Carpenters",
"The Cars",
"CAT STEVENS",
"Charlie Daniels Band",
"Cheap Trick",
"Cher",
"Chic",
"Chicago",
"Chicken Shack",
"Chi-Lites",
"Chilliwack",
"Chuck Berry",
"Chuck Brown",
"The Cigarettes",
"The Clash",
"Climax Blues Band",
"Cold Blood",
"Cold Chisel",
"Commander Cody",
"The Commodores",
"Creedence Clearwater Revival",
"Crosby Stills Nash & Young",
"Curtis Mayfield",
"Dave Clark Five",
"DAVID BOWIE",
"DEEP PURPLE",
"DELANEY AND BONNIE",
"Delfonics",
"DEREK AND DOMINOES",
"Diana Ross",
"Dionne Warwick",
"Dire Straits",
"Dixie Dregs",
"Don McLean",
"Donna Summer",
"Donny Osmond",
"Doobie Brothers",
"The Doors",
"Dorothy Moore",
"Doug & The Slugs",
"Dr. Feelgood",
"Dr. Hook & The Medicine Show",
"Dragon",
"Dust",
"Eagles",
"Earth, Wind & Fire",
"Eddie & the Hot Rods",
"Eddie Money",
"Edgar Broughton Band",
"Edgar Winter Group",
"Electric Light Orchestra",
"Elf",
"Elton John",
"Elvin Bishop",
"Elvis Costello",
"Elvis Presley",
"The Emotions",
"Emerson, Lake & Palmer",
"England Dan & John Ford Coley",
"ERIC CLAPTON",
"Eruption",
"Faces",
"FACES",
"Fanny",
"Fats Domino",
"Fifth Dimension",
"Firefall",
"The First Edition",
"Fleetwood Mac",
"Flying Burrito Brothers",
"Focus",
"Foghat",
"Foreigner",
"The Four Seasons",
"The Four Tops",
"FRANK ZAPPA",
"Freddie Fender",
"Free",
"Frijid Pink",
"Funkadelic",
"Gap Band",
"Gary Glitter",
"Gary Wright",
"Generation X",
"Genesis",
"Geordie",
"George Clinton",
"GEORGE HARRISON",
"George Thorogood & The Destroyers",
"Gerry Rafferty",
"Gino Vanelli",
"Gladys Knight",
"Glenn Hughes",
"Gloria Gaynor",
"The Go Go's",
"Golden Earring",
"Gordon Lightfoot",
"Grand Funk Railroad",
"The Grateful Dead",
"The Groundhogs",
"The Guess Who",
"H. P. Lovecraft",
"Hall & Oates",
"Harlequin",
"Harry Chapin",
"Harry Nilsson",
"Hawkwind",
"Head East",
"Heart",
"Helen Reddy",
"Hello",
"The Hollies",
"Hoodoo Rhythm Devils",
"Horslips",
"Hot Chocolate",
"Hotlegs",
"HOT TUNA",
"HOUND DOG TAYLOR",
"The Human League",
"Humble Pie",
"Ian Gillian Band",
"Ian Hunter",
"Iggy Pop",
"Ike & Tina Turner",
"Iron Butterfly",
"Iron Virgin",
"Isaac Hayes",
"Isis",
"Isley Brothers",
"The J. Geils Band",
"J.J. CALE",
"Jack the Lad",
"Jackson 5",
"Jackson Browne",
"JAMES GANG",
"James Taylor",
"JANIS JOPLIN",
"Jeff Beck",
"JEFFERSON AIRPLANES",
"JETHRO TULL",
"Jim Croce",
"Jimmy Buffett",
"JO JO GUNNE",
"JOE COCKER",
"JOE COCKER MAD DOGS AND ENGLISHMAN",
"Joe Jackson",
"JOE WALSH",
"John Denver",
"John Hiatt",
"John Lennon",
"John Lee Hooker",
"Johny Barbata",
"Johnny Thunders & The Heartbreakers",
"JOHNNY WINTER",
"Joni Mitchell",
"Journey",
"Joy Division",
"Judas Priest",
"K. C. & The Sunshine Band",
"Kansas",
"Kenny Loggins",
"Kenny Rogers",
"Kentucky Headhunters",
"Killing Joke",
"Kim Carnes",
"King Crimson",
"KINKS",
"Kiss",
"Klaatu",
"The Knack",
"Kool & The Gang",
"Kraftwerk",
"L. T. D.",
"LED ZEPPLIN",
"Legs Diamond",
"Leo Sayer",
"Leonard Cohen",
"Linda Ronstadt",
"Lipps Inc",
"Little Feat",
"Little River Band",
"Loggins & Messina",
"Lou Rawls",
"Lou Reed",
"LYNYRD SKYNRYD",
"MC 5",
"MAGGIE BELL",
"Mahogany Rush",
"Manfred Mann's Earth Band",
"The Manhattans",
"Mark-Almond Band",
"Marshall Tucker Band",
"Marvin Gaye",
"Max Webster",
"Meat Loaf",
"Medicine Head",
"Michael Jackson",
"Michael Nesmith",
"Michael Stanley Band",
"The Miracles",
"Moby Grape",
"Molly Hatchet",
"Montrose",
"MOODY BLUES",
"Motorhead",
"The Motors",
"Mott the Hoople",
"MOUNTAIN/LESLIE WEST",
"Moxy",
"Mungo Jerry",
"Nazareth",
"Neil Diamond",
"Neil Young",
"New Riders of the Purple Sage",
"New York Dolls",
"Nick Lowe",
"Ocean",
"The O'Jays",
"Ohio Players",
"Olivia Newton-John",
"The Outlaws",
"Ozark Mountain Daredevils",
"Pablo Cruise",
"Parliament",
"The Partridge Family",
"Pat Benatar",
"Pat Metheny Group",
"Pat Travers",
"PATTI SMITH",
"PAUL McCARTNEY",
"Paul Revere & The Raiders",
"Paul Simon",
"Pentagram",
"PETER FRAMPTON",
"Peter Green",
"PINK FLOYD",
"Poco",
"Point Blank",
"Pointer Sisters",
"The Police",
"Pretty Things",
"PROCOL HARUM",
"Pure Prarie League",
"Queen",
"Quicksilver Messenger Service",
"Quiet Riot",
"Rainbow",
"Ram Jam",
"Ramones",
"Rare Earth",
"Raspberries",
"Ray Charles",
"Ray Stevens",
"Red Rider",
"REO Speedwagon",
"Rick Derringer",
"Rick Springfield",
"Ringo Starr",
"Roberta Flack",
"ROBIN TROWER",
"ROD STEWART",
"Rodriguez",
"Rolling Stones",
"Rose Tatoo",
"Roxy Music",
"The Runaways",
"Rush",
"RY COODER",
"SANTANA",
"Scorpions",
"Seals & Crofts",
"Sensational Alex Harvey Band",
"Sex Pistols",
"Shaun Cassidy",
"Simon & Garfunkel",
"Simple Minds",
"Siouxsie and the Banshees",
"Sir Lord Baltimore",
"Skyhooks",
"Slade",
"Sly & The Family Stone",
"Smokie Robinson & The Miracles",
"The Spinners",
"Spirit",
"The Staple Singers",
"Status Quo",
"Stealers Wheel",
"STEELY DAN",
"Steppenwolf",
"Steve Harley & Cockney Rebel",
"STEVE MILLER BAND",
"Steven Van Zandt",
"Stevie Wonder",
"The Stooges",
"Stranglers",
"Stray",
"Styx",
"Supertramp",
"Supremes",
"Suzi Quatro",
"Sweet",
"T. Rex",
"Talking Heads",
"Tangerine Dream",
"Taste of Honey",
"Ted Nugent",
"The Temptations",
"TEN YEARS AFTER/ALVIN LEE",
"Terry Jacks",
"Thin Lizzy",
"Three Dog Night",
"Thundermug",
"Tim Curry",
"Todd Rundgren",
"Tom Jones",
"Tom Waits",
"Tommy Bolin",
"Tony Orlando & Dawn",
"Toto",
"Traffic",
"Triumph",
"Twisted Sister",
"U2",
"UFO",
"Uriah Heep",
"VAN HALEN",
"Van Morrison",
"Village People",
"Vinegar Joe",
"War",
"Warhorse",
"Warm Dust",
"Warren Zevon",
"THE WHO",
"Wicked Lester",
"Widowmaker",
"Wild Cherry",
"Wings",
"Wishbone Ash",
"Wizzard",
"YES",
"Yesterday & Today",
"ZZ TOP",
"Zoot"
]

eightiesArtists = [
"Michael Jackson",
"Prince",
"Madonna",
"U2",
"Bruce Springsteen",
"Run-D.M.C.",
"Van Halen",
"Public Enemy",
"Billy Joel",
"The Police",
"Phil Collins",
"Guns N Roses",
"Def Leppard",
"Janet Jackson",
"George Michael",
"Wham",
"Whitney Houston",
"Metallica",
"N.W.A",
"Dire Straits",
"AC/DC",
"Rush",
"Iron Maiden",
"Judas Priest",
"Lionel Richie",
"Bon Jovi",
"Talking Heads",
"Genesis",
"R.E.M.",
"Duran Duran",
"Motley Crue",
"The Cure",
"Journey",
"John Mellencamp",
"Grandmaster Flash & The Furious Five",
"REO Speedwagon",
"Kool and the Gang",
"L.L. Cool J",
"Tina Turner",
"Queen",
"Beastie Boys",
"Ozzy Osbourne",
"The Smiths",
"Huey Lewis and the News",
"Bryan Adams",
"Hall & Oates",
"Pat Benatar",
"Eric B. & Rakim",
"Billy Idol",
"Peter Gabriel",
"INXS",
"Tom Petty & the Heartbreakers",
"Stevie Ray Vaughan & Double Trouble",
"Eurythmics",
"The Cars",
"Aerosmith",
"ZZ Top",
"The Rolling Stones",
"Heart",
"David Bowie",
"Elton John",
"Rod Stewart",
"Foreigner",
"Stevie Wonder",
"Toto",
"Bob Seger",
"The Pointer Sisters",
"DJ Jazzy Jeff & The Fresh Prince",
"Salt-N-Pepa",
"Fleetwood Mac",
"The Go-Gos",
"Paul McCartney",
"Pet Shop Boys",
"Don Henley",
"Paul Simon",
"Tracy Chapman",
"Cyndi Lauper",
"Depeche Mode",
"Sonic Youth",
"Pete Townshend",
"Culture Club",
"Gloria Estefan Miami Sound Machine",
"De La Soul",
"Luther Vandross",
"Chicago",
"The Bangles",
"Thompson Twins",
"Yes",
"Men at Work",
"Pixies",
"Pink Floyd",
"Robert Palmer",
"Kenny Loggins",
"Whitesnake",
"Sade",
"Steve Winwood",
"Billy Ocean",
"Tears for Fears",
"Bobby Brown",
"Scorpions",
"Simply Red",
"B-52s",
"Boston",
"Rick James",
"Joan Jett",
"Stevie Nicks",
"Berlin",
"Sting",
"New Order",
"Poison",
"The Pretenders",
"Quiet Riot",
"RATT",
"The Clash",
"The Stone Roses",
"Squeeze",
"Styx",
"Frankie Goes to Hollywood",
"New Edition",
"Stray Cats",
"Paula Abdul",
"The Human Leagu",
"Violent Femmes",
"Elvis Costello",
"A-Ha",
"Blondie",
"Eddie Money",
"Anita Baker",
"Sheena Easton",
"Loverboy",
"Asia",
"Skid Row",
"Tiffany",
"Debbie Gibson",
"Crosby Stills Nash (& Young)",
"Madness",
"Aretha Franklin",
"Afrika Bambaataa",
"UB 40",
"Patti LaBelle",
"Tone-Loc",
"Falco",
"Simple Minds",
"Earth Wind & Fire",
"KISS",
"The Jam",
"Marvin Gaye",
"Bananarama",
"New Kids on the Block",
"Billy Squier",
"Slayer",
"Adam Ant",
"Spandau Ballet",
"Milli Vanilli",
"The Jesus and Mary Chain",
"ABC",
"Cinderella",
"Bonnie Raitt",
"10,000 Maniacs",
"Accept",
"Eric Clapton",
"Kool Moe Dee",
"The Cult",
"The Fixx",
"Air Supply",
"Richard Marx",
"Bruce Hornsby & the Range",
"Starship",
"The Replacements",
"Fine Young Cannibals",
"Mr. Mister",
"Boogie Down Productions",
"Irene Cara",
"David Lee Roth",
"Twisted Sister",
"Corey Hart",
"Doug E. Fresh",
"Laura Branigan",
"Dio",
"Dokken",
"A Flock of Seagulls",
"Eddy Grant",
"Black Flag",
"Dead Kennedys",
"George Thorogood",
"John Lennon",
"Terence Trent Darby",
"Red Hot Chili Peppers",
"Rick Springfield",
"Paul Young",
"Black Sabbath",
"Howard Jones",
"Orchestral Manoeuvres in the Dark",
"Level 42",
"Europe",
"Tom Waits",
"Mike Oldfield",
"Chris De Burgh",
"Alan Parsons Project",
"John Farnham"
]

ninetiesArtists = [
"2Pac",
"Mariah Carey",
"Pearl Jam",
"Madonna",
"R.E.M.",
"U2",
"Dr. Dre",
"Red Hot Chili Peppers",
"The Smashing Pumpkins",
"The Notorious B.I.G",
"OutKast",
"Janet Jackson",
"Green Day",
"Fugees/Lauryn Hill",
"Metallica",
"Ice Cube",
"Oasis",
"TLC",
"Alice In Chains",
"Snoop Dogg",
"Nine Inch Nails",
"Nas",
"Beastie Boys",
"Rage Against The Machine",
"Jay-Z",
"A Tribe Called Quest",
"Mary J. Blige",
"Beck",
"Soundgarden",
"Public Enemy",
"Wu-Tang Clan",
"Alanis Morissette",
"Guns N Roses",
"Queen Latifah",
"Dave Matthews Band",
"No Doubt",
"Prince",
"Michael Jackson",
"R. Kelly",
"En Vogue",
"Tori Amos",
"Missy Elliot",
"Jeff Buckley",
"Weezer",
"PJ Harvey",
"Blur",
"Tool",
"Sonic Youth",
"Stone Temple Pilots",
"Jane's Addiction",
"Eric Clapton",
"Boyz II Men",
"Seal",
"Bush",
"Fugazi",
"Sinead O' Conner",
"Cypress Hill",
"The Roots",
"The Offspring",
"Neil Young",
"Sublime",
"Marilyn Manson",
"Pantera",
"Liz Phair",
"Pavement",
"Coolio",
"Korn",
"Foo Fighters",
"My Bloody Valentine",
"Black Crowes",
"Silver Chair",
"The Verve",
"Phish",
"311",
"Hole",
"The Flaming Lips",
"Lenny Kravitz",
"Nick Cave & The Bad Seeds",
"Sheryl Crow",
"Megadeth",
"Faith No More",
"Queen",
"The Cranberries",
"Busta Rhymes",
"Warren G.",
"The Mighty Mighty Bosstones",
"Kenny Wayne Shepherd Band",
"D Angelo",
"Creed",
"Arrested Development",
"Blind Melon",
"Manic Street Preachers",
"Garbage",
"Screaming Trees",
"Hootie & The Blowfish",
"Primus",
"Wilco"
]

#Artists to bump manually
#Nirvana

def writeFile(filename, msg):
  filename = os.path.join('logs', filename)
  text_file = open(filename, "a")
  text_file.write(msg + "\n")
  text_file.close()

def writeLog(filename, msg):
  writeFile(filename + ".txt", msg)

test = [
'Oasis'
]

artistsBumped = 0
for artist in test:
  print "------------------------------------------------------------"
  print "current artist", artist
  artistLowercase = artist.lower()
  artistEncoded = urllib2.quote(artistLowercase)
  # actually need to call last fm to get mbid as it's much more robust
  headers={
    "User-Agent" :
    "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
  }
  url="http://localhost:5000/search?query=" + artistEncoded + "&type=artist&method=indexed"


  r = requests.get(url, headers=headers)
  soup = BeautifulSoup(r.content, "html.parser")
  trs = soup.findAll("tr")
  td1 = trs[1].findAll('td')[0]
  topScore  = td1.getText()

  if topScore  == "100":
    tr1 = trs[1]
    td1 = tr1.findAll('td')[1]
    if td1.find('bdi').getText().lower() == artistLowercase:
      artistsBumped += 1
      link = td1.find('a')
      artistMbid = link['href'].replace('/artist/', '')

      lastFmUrl = "http://ws.audioscrobbler.com/2.0/?method=artist.search&artist=" + artistEncoded + "&api_key=57ee3318536b23ee81d6b27e36997cde&format=json&limit=1"
      lastFmRequest = requests.get(lastFmUrl, headers=headers)
      lastFmJsonResponse = json.loads(lastFmRequest.content)
      lastFmMbid = lastFmJsonResponse['results']['artistmatches']['artist'][0]['mbid']
      print "L", lastFmMbid
      # Cross reference lastfm and musicbrainz results
      if artistMbid == lastFmMbid:
        elasticSearchUrl = 'http://localhost:9200/artists/artist/' + artistMbid
        elasticSearchRequest = requests.get(elasticSearchUrl, headers=headers)
        jsonResponse = json.loads(elasticSearchRequest.content)
        views = jsonResponse['_source']['views']

        if views == 200:
          # make a request to bump the views by 100
          data = { "script" : "ctx._source.views+=100" }
          payload = json.dumps(data)
          try:
            requests.post(elasticSearchUrl + "/_update", headers=headers, data=payload)
            print "-- Bumping! Artists bumped so far", artistsBumped
            releaseGroupsUrl = "http://localhost:5000/ws/2/release-group/?query=arid:%22" + artistMbid + "%22%20AND%20type:%22album%22%20AND%20status:%22official%22&fmt=json"

            releaseGroupData = requests.get(releaseGroupsUrl)
            releaseGroupsJson = json.loads(releaseGroupData.content)
            releaseGroups = releaseGroupsJson['release-groups']
            print "-- Saving release groups: ", len(releaseGroups)
            for releaseGroup in releaseGroups:
              writeLog('release-group', releaseGroup['id'])

            # call last fm and get all related artists and log those to a file (to be run against this script later)
            lastFmSimilarArtistsUrl = "http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&artist=" + artistEncoded + "&api_key=57ee3318536b23ee81d6b27e36997cde&format=json&limit=40"
            lastFmSimilarArtistsRequest = requests.get(lastFmSimilarArtistsUrl, headers=headers)
            lastFmJsonSimilarArtistsResponse = json.loads(lastFmSimilarArtistsRequest.content)
            similarArtists = lastFmJsonSimilarArtistsResponse['similarartists']['artist']
            print "-- Saving similar artists: ", len(similarArtists)
            for artist in similarArtists:
              try:
                if artist['mbid']:
                  writeLog('similar-artist', artist['name'] + artist['mbid'])
              except:
                continue
          except urllib2.HTTPError, e:
            print "-- Some error in bumping view score or getting release data"
            writeLog('error-check-artist-bump', artistMbid)

        else :
          # log that artist has been already bumped
          writeLog('artist-already-bumped', artistMbid)
          print "--", jsonResponse['_source']['name'], "already bumped, views:", jsonResponse['_source']['views']
      else :
        print "Lastfm and Musicbrainz not matching lastfm =", lastFmMbid, "musicbrainz mbid =", artistMbid
        # log here
        logString = "mbid: " + artistMbid +  " lastFMMbid: " +  lastFmMbid
        writeLog('ids-not-matching', logString)
    else:
      print "-- Artist name no match"
      # write a log file that artist names dont match
      writeLog('artist-name-no-match', artistLowercase)

  else:
    print "-- First cell not top score"
    # make a log here
    writeLog('first-cell-not-100', artistLowercase)
  time.sleep(2)
